config/routes.rb
Rails.application.routes.draw do
  resources :stocks, only: [:index]
  resources :stock_transactions, only: [:new, :create, :index]
  resources :admin, only: [:index]
  resources :trader, controller: 'users'
  resources :transactions, only: [:create, :index]
  get 'transactions/new/:transaction_type(/:symbol)', to: 'transactions#new', as: 'new_transaction'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  namespace :market do
    resources :stocks, only: [:index, :show]
  end

  
  get 'home', to: 'static_pages#home'
  get 'admin/all', to: 'admin#all'
  get 'admin/transactions', to: 'admin#transactions'
  get 'admin/pending', to: 'admin#pending'
  get 'users/approval', to: 'users#approval'
  post 'traders', to: 'users#create'
  
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :stock
  belongs_to :user
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :transactions
  has_many :shares
  has_many :users, through: :shares

  def data 
    self.chart == [] ? Stock.first.chart : self.chart
  end
end

app/models/stock_transaction.rb
class StockTransaction < ApplicationRecord
  belongs_to :stock
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates_presence_of :amount

  belongs_to :stock, optional: true
  belongs_to :user

  after_create :update_user_shares_and_balance

  private

  def update_user_shares_and_balance
    if stock_id
      share = user.shares.find_or_create_by(stock_id:)
      share.value = changed_share_value(share.value)
      user.balance = calculate_balance(share.stock.price)
      user.save!
      share.save!
    else
      update_user_balance
    end
  end

  def update_user_balance
    if transaction_type == 'deposit'
      user.balance += amount 
    elsif transaction_type == 'withdraw'
     user.balance -= amount 
    end
    user.save!
  end

  def calculate_balance(price)
    if transaction_type == 'sell'
      user.balance + amount * price  
    elsif transaction_type == 'buy'
     user.balance - amount * price  
    end
  end

  def changed_share_value(value)
    if transaction_type == 'sell'
      value - amount
    elsif transaction_type == 'buy'
      amount + value
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :transactions
  has_many :shares
  has_many :stocks, through: :shares
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end

  enum pending: [:waiting, :approved]
  after_initialize :set_default_pending, :if => :new_record?
  def set_default_pending
    self.role ||= :waiting
  end
  
  has_many :stock_transactions
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_admin
  layout 'admin'
  
  def index
    @users = User.all
    @pending = User.where(pending: "waiting", role: 0)
    @newuser = User.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day, role: 0)
  end

  def all
    @users = User.all.where(role: 0)
  end

  def transactions
  end

  def pending
    @users = User.all
    @pending = User.where(pending: "waiting", role: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_index_path
    else current_user.user?
      if current_user.waiting?
        users_approval_path
      else
        root_path
      end
    end
  end
  
  private
    def check_admin
      unless current_user.role == "admin"
        redirect_back fallback_location: root_path
      end
    end
    def check_user
      unless current_user.role == "user"
        redirect_back fallback_location: admin_index_path
      end
    end
    def check_pending
      unless current_user.pending == "approved"
        redirect_to users_approval_path
      end
    end
end

app/controllers/market/stocks_controller.rb
class Market::StocksController < ApplicationController
  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  layout 'devise'

  def home
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :check_user
  before_action :check_pending

  def index
    unless user_signed_in?
      redirect_to home_path 
    else
      @shares = current_user.shares.includes(:stock)
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :check_pending

  def new
    @stock = Stock.find_by_symbol(params[:symbol]) 
    @transaction_type = params[:transaction_type]
    
    @transaction = Transaction.new
  end

  def index
    @transactions = current_user.transactions.includes(:stock).order(created_at: :desc)
  end

  def create
    @transaction = current_user.transactions.new(transaction_params)

    if @transaction.save
      redirect_to stocks_path, notice: "your transaction is successful"
    else
      redirect_to new_transaction_path(@transaction.transaction_type), alert: @transaction.errors.first.full_message
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount, :stock_id, :transaction_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_user, only: [:index, :approval]
  before_action :check_pending, only: [:index]
  layout 'admin', only: [:show, :edit, :update, :new, :create]

  def index
  end

  def approval
  end

  def show
  end

  def new 
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_all_path,  notice: 'The user has been created.'
    else
      render :new, alert: @user.errors.first.full_message
    end
  end

  def update
    if @user.update!(user_params)
      redirect_to admin_all_path, notice: 'The user has been updated.'
      if user_params.has_key?(:pending)
        ApprovedMailer.with(user: @user).approved_mail.deliver_now
      end
    else
      render :edit
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:pending, :email, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/market/stocks_helper.rb
module Market::StocksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stock_transactions_helper.rb
module StockTransactionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/all.html.erb
<div class='p-7 h-screen'>
  <div class='h-1/6 flex flex-row justify-between items-center p-5'>
    <div class='text-3xl font-bold'>All Users</div>
    <div class='p-3 text-center border-2 border-black rounded-xl font-bold'><%= link_to 'Add', new_trader_path %></div>
  </div>
  <table class='w-full'> 
    <tr class='font-bold'>
      <th class='w-1/6'> ID </th>
      <th class='w-1/6'> Role </th>
      <th class='w-1/6'> Email </th>
      <th class='w-1/6'> Created at </th>
      <th class='w-1/6'> Status </th>
    </tr>
    <% @users.each do |user| %>
    <tr class='text-center'>
      <td class=''><%= user.id %></td>
      <td class='uppercase'><%= user.role %></td>
      <td class=''><%= link_to user.email, trader_path(user.id) %></td>
      <td class='uppercase'><%= user.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td>
      <% if user.pending == "waiting" %>
        <button class='bg-red-400 uppercase p-1 rounded-2xl border-2 border-solid border-black '> <%= user.pending %> </button>
      <% else %>
        <button class='bg-green-400 uppercase p-1 rounded-2xl border-2 border-solid border-black '> <%= user.pending %> </button>
      <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/index.html.erb
<div class='p-7 h-screen'>
  <div class='h-1/6 flex flex-row justify-between items-center p-5'>
    <div class='text-3xl font-bold'>Dashboard</div>
    <div class='p-3 text-center border-2 border-black rounded-xl font-bold'><%= link_to 'Add', new_trader_path %></div>
  </div>
  <div class='h-1/6 flex flex-row justify-between p-5 text-center font-bold content-center'>
    <div class='flex items-center justify-center m-4 border border-black rounded-xl w-2/6 content-center'><%= @users.count %><br>Total Users</div>
    <div class='flex items-center justify-center m-4 border border-black rounded-xl w-2/6'><%= @pending.count %><br>Pending Users  </div>
    <div class='flex items-center justify-center m-4 border border-black rounded-xl w-2/6'>0<br>Total Money </div>
    <div class='flex items-center justify-center m-4 border border-black rounded-xl w-2/6'>0<br>Total Transactions </div>
  </div>
  <div class='h-4/6 flex flex-row '>
    <div class='p-5 m-4 border border-black rounded-xl w-3/4'>
      <div class='font-bold'>New Users </div>
      <div class='flex flex-col'>
        <% @newuser.each do |newuser| %>
        <div class='flex flex-row'>
            <div class='w-1/5'><%= newuser.id %></div>
            <div class='w-1/5'><%= newuser.role %></div>
            <div class='w-1/5'><%= newuser.email %></div>
            <div class='w-1/5'><%= newuser.created_at.to_time.strftime('%B %e at %l:%M %p') %></div>
            <div class='flex justify-center w-1/5'><%= newuser.pending %></div>
        </div>
        <% end %>
      </div>
    </div>
    <div class='p-5 m-4 border border-black rounded-xl w-1/4 font-bold'> Latest Transactions </div>
  </div>
</div>

app/views/admin/pending.html.erb
<div class='p-7 h-screen'>
  <div class='h-1/6 flex flex-row justify-between items-center p-5'>
    <div class='text-3xl font-bold'>Pending Users</div>
    <div class='p-3 text-center border-2 border-black rounded-xl font-bold'><%= link_to 'Add', new_trader_path %></div>
  </div>
  <table class='w-full'> 
    <tr class='font-bold'>
      <th class='w-1/6'> ID </th>
      <th class='w-1/6'> Role </th>
      <th class='w-1/6'> Email </th>
      <th class='w-1/6'> Created at </th>
      <th class='w-1/6'> Status </th>
    </tr>
    <% @pending.each do |user| %>
    <tr class='text-center'>
      <td class=''><%= user.id %></td>
      <td class='uppercase'><%= user.role %></td>
      <td class=''><%= link_to user.email, trader_path(user.id) %></td>
      <td class='uppercase'><%= user.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td>
        <%= button_to user.pending, trader_path(user), method: :patch,
                  params: {
                    'user' => {
                        'pending' => 'approved',
                      }
                  },
                  class: 'bg-red-400 uppercase p-1 rounded-2xl border-2 border-solid border-black' %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/transactions.html.erb
<div class='p-7 h-screen'>
  <div class='h-1/6 flex flex-row justify-between items-center p-5'>
    <div class='text-3xl font-bold'>Transactions</div>
    <div class='p-3 text-center border-2 border-black rounded-xl font-bold'><%= link_to 'Add', new_trader_path %></div>
  </div>
  <div class='flex flex-col'>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethpros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <main class="bg-white relative overflow-hidden h-screen">
      <div class='flex h-screen'>
        <div class='w-1/5 bg-zinc-500 flex flex-col p-10 text-white text-lg'>
          <div class='flex justify-center p-5'> 
            <div class='text-4xl'>Admin</div>
            <div class='text-4xl text-blue-800'>.</div>
          </div>
          <div class='h-full flex flex-col justify-between'>
            <div class=''>
              <div class='p-4'><%= link_to "Dashboard", admin_index_path %></div>
              <div class='p-4'><%= link_to "All Users", admin_all_path %></div>
              <div class='p-4'><%= link_to "Pending Users", admin_pending_path %></div>
              <div class='p-4'><%= link_to "Transactions", admin_transactions_path %></div>
            </div>
            <div>
              <div class='p-4 text-center border border-white rounded-xl font-bold'><%= button_to "Logout", destroy_user_session_path, method: :delete %></div>
            </div>
          </div>
        </div>
        <div class='w-4/5 bg-zinc-50'>
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethpros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <main class="grid grid-cols-[auto_1fr] grid-rows-[auto_1fr] h-screen w-screen">
      <header class="h-24 w-full flex items-center justify-between px-16 gap-16 border-b border-b-gray-300 relative">
        <%= render 'layouts/shared/flash' %>
        <div class="flex-1 relative">
          <input type="text" 
                 name="search" 
                 placeholder="Search for stock market"
                 class="block p-2 pr-10 w-full text-lg text-gray-900 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500">
          <%= vite_image_tag 'icons/search.svg', class: 'h-8 w-8 absolute bottom-2 right-2.5' %>
        </div>

        <div class="font-bold text-lg text-gray-600">
          Balance: <span class="text-green-600 text-xl">$<%= current_user.balance %></span> 
        </div>

        <button class="block h-8 w-8"><%= vite_image_tag 'icons/bell.svg' %></button>

        <div class="flex gap-2 items-center">
          <img src="https://avatars.dicebear.com/api/initials/<%= current_user.email %>.svg" 
               alt="user avatar"
               class="h-12 w-12 rounded-full"
               >
          <h3 class="text-xl font-semibold text-gray-800"><%= current_user.email %></h3>
        </div>

      </header>
      <nav class="row-start-1 row-span-2 w-96 p-10 flex flex-col bg-gray-100 gap-4">
        <div class="p-4">
          <h1 class="text-center text-4xl font-black text-gray-900 font-mono">EthPros</h1>
        </div>
        <ul class="flex-1 border-t-2 border-b-2 border-t-gray-400 border-b-gray-400 flex flex-col gap-4 py-8">
          <li>
            <%= link_to root_path do %>
              <div class="text-gray-600 text-xl font-medium flex gap-4">
                <%= vite_image_tag 'icons/dashboard.svg', class: 'h-8 stroke-g4ay-600' %>
                Dashboard
              </div>
            <% end %>
          </li>
          <li>
            <%= link_to market_stocks_path do %>
              <div class="text-gray-600 text-xl font-medium flex gap-4">
                <%= vite_image_tag 'icons/market.svg', class: 'h-8 stroke-gray4600' %>
                Market
              </div>
            <% end %>
          </li>
          <li>
            <%= link_to stocks_path do %>
              <div class="text-gray-600 text-xl font-medium flex gap-4">
                <%= vite_image_tag 'icons/portfolio.svg', class: 'h-8 stroke-g4ay-600' %>
                Portfolio
              </div>
            <% end %>
          </li>
          <li>
            <%= link_to transactions_path do %>
              <div class="text-gray-600 text-xl font-medium flex gap-4">
                <%= vite_image_tag 'icons/transactions.svg', class: 'h-8 stroke-g4ay-600' %>
              Transactions
              </div>
            <% end %>
          </li>
          <li>
            <%= link_to new_transaction_path('deposit') do %>
              <div class="text-gray-600 text-xl font-medium flex gap-4">
                <%= vite_image_tag 'icons/transactions.svg', class: 'h-8 stroke-g4ay-600' %>
              Deposit
              </div>
            <% end %>
          </li>
          <li>
            <%= link_to new_transaction_path('withdraw') do %>
              <div class="text-gray-600 text-xl font-medium flex gap-4">
                <%= vite_image_tag 'icons/transactions.svg', class: 'h-8 stroke-g4ay-600' %>
              Withdraw
              </div>
            <% end %>
          </li>
        </ul>
        <%=
          button_to 'Logout',
                    destroy_user_session_path,
                    method: :delete,
                    class:
                      'bg-gray-200 text-gray-900 p-2 rounded-md text-md font-bold text-center w-full'
        %>
      </nav>
      <section class="bg-gray-800 flex justify-center items-center h-full w-full">
        <%= yield %>
      </section>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethpros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <main class="bg-white relative overflow-hidden h-screen">
      <header class="h-24 sm:h-32 flex items-center z-30 w-full relative">
        <div class="absolute -bottom-10 w-full">
        <% if notice %>
          <p class="text-center text-xl font-semibold text-gray-50 bg-blue-500 py-2"> &#128276; <%= notice %> </p>
        <% end %>
        <% if alert %>
          <p class="text-center text-xl font-semibold text-gray-50 bg-red-500 py-2">&#9888;&#65039; <%= alert %></p>
        <% end %>
        </div>
        <div class="container mx-auto px-6 flex items-center justify-between">
          <div class="uppercase text-gray-800 font-black text-3xl">
            <h1>EthPros</h1>
          </div>
          <div class="flex items-center">
            <nav
              class="font-sen text-gray-800 uppercase text-lg lg:flex items-center hidden"
            >
              <a
                href="#"
                class="py-2 px-6 flex text-gray-500 border-b-2 border-gray-500"
              >
                Home
              </a>
              <a href="#" class="py-2 px-6 flex hover:text-gray-500">
                Pricing
              </a>
              <%=
                link_to 'Signup',
                        new_user_registration_path,
                        class: 'py-2 px-6 flex hover:text-gray-500'
              %>
              <%=
                link_to 'Login',
                        new_user_session_path,
                        class:
                          'py-2 px-6 flex hover:text-gray-100 hover:bg-gray-800 bg-gray-500 rounded-lg text-white'
              %>
            </nav>
            <button class="lg:hidden flex flex-col ml-4">
              <span class="w-6 h-1 bg-gray-800 mb-1"> </span>
              <span class="w-6 h-1 bg-gray-800 mb-1"> </span>
              <span class="w-6 h-1 bg-gray-800 mb-1"> </span>
            </button>
          </div>
        </div>
      </header>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% if notice %>
  <div
    class="absolute h-14 w-full bg-blue-500 -bottom-14 right-0 flex items-center justify-center z-50"
  >
    <p class="text-gray-100 font-bold text-lg">&#128276; <%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div
    class="absolute h-14 w-full bg-red-500 -bottom-14 right-0 flex items-center justify-center z-50"
  >
    <p class="text-gray-100 font-bold text-lg">&#128276; <%= alert %></p>
  </div>
<% end %>