config/routes.rb
Rails.application.routes.draw do
  resources :stocks, only: [:index]
  resources :stock_transactions, only: [:new, :create, :index]
  resources :admin, only: [:index]
  resources :trader, controller: 'users'
  resources :transactions, only: [:create, :index]
  get 'transactions/new/:transaction_type(/:symbol)', to: 'transactions#new', as: 'new_transaction'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  namespace :market do
    resources :stocks, only: [:index, :show]
  end

  
  get 'home', to: 'static_pages#home'
  get 'admin/all', to: 'admin#all'
  get 'admin/transactions', to: 'admin#transactions'
  get 'admin/pending', to: 'admin#pending'
  get 'users/approval', to: 'users#approval'
  post 'traders', to: 'users#create'
  
  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :transactions
  has_many :shares
  has_many :stocks, through: :shares
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end

  enum pending: [:waiting, :approved]
  after_initialize :set_default_pending, :if => :new_record?
  def set_default_pending
    self.role ||= :waiting
  end
  
  has_many :stock_transactions
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:cancel ]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: :cancel 
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_user, only: [:index, :approval]
  before_action :check_pending, only: [:index]
  layout 'admin', only: [:show, :edit, :update, :new, :create]

  def index
  end

  def approval
  end

  def show
  end

  def new 
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_all_path,  notice: 'The user has been created.'
    else
      render :new, alert: @user.errors.first.full_message
    end
  end

  def update
    if @user.update!(user_params)
      redirect_to admin_all_path, notice: 'The user has been updated.'
      if user_params.has_key?(:pending)
        ApprovedMailer.with(user: @user).approved_mail.deliver_now
      end
    else
      render :edit
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:pending, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/approval.html.erb
<div class='flex flex-col justify-center items bg-white w-5/6 h-5/6 bg-gradient-to-r from-cyan-500 to-blue-500'>
<div class='p-10 w-full flex flex-col justify-center items-center'>
  <div><img class='h-96 w-96' src="https://img.freepik.com/free-vector/raining-concept-illustration_114360-4054.jpg?w=740&t=st=1657532210~exp=1657532810~hmac=04b8de158163a41579e62b031f094f6fcd58891b84900273a83b1034be543059"></div>
  <div class='font-bold text-5xl py-4'> Sorry </div>
  <div class='text-xl pt-4'> We are still waiting for the admin to approve your account! </div>
  <div class='text-xl'> We'll let you know once your account has been approved. </div>
  <div class='text-xl'> Come back once your account has been approved! </div>
</div>

</div>

app/views/users/edit.html.erb
<div class='flex justify-center content-center text-center flex-col w-auto'>
  <div class='font-bold pt-64 pb-10 text-5xl'> Edit User </div>
  <div class='flex w-96 justify-center content-center self-center'>
    <%= form_with model: @user, url: edit_trader_path(@user) do |form| %>
      <div class="category-detail-list">
        <div class="category-add">
          <div class="field">   
            <%= form.label :email, class: "text-left font-bold"%></br>
            <%= form.email_field :email, class: "block border-1 border-black" %>
          </div>
        </div>
        <div class="category-add">
          <div class="field"></br>
            <%= form.label :password, class: "font-bold" %></br>
            <%= form.password_field :password, class: "block border-1 border-black" %></br>
          </div>
        </div>
      <div class="submit"></br>
        <button class='text-xl font-bold bg-cyan-500 uppercase p-1 rounded-2xl border-2 border-solid border-black w-48'><%= form.submit "Submit", class: "button-form" %></button>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="w-[90%] h-[90%] bg-gray-50 flex flex-col justify-between">
  <div class="h-24 flex items-end bg-gray-800">
    <div class="bg-gray-50 h-full flex-1 relative p-4">
      <div
        class="absolute bg-gray-800 -top-7 -right-7 origin-[50%_50%] rotate-45 w-14 h-14"
      ></div>
      <h2 class="text-4xl font-bold text-gray-900">Wallet</h2>
    </div>
    <div class="bg-gray-50 h-3/5 w-5/12"></div>
  </div>

  <div class="h-16 bg-gray-50 border-t-2 border-b-2 flex">
    <h1 class="flex-1 flex items-center px-4 text-2xl text-gray-700 font-light">Balance: $40,000,000</h1>
    <button class="flex gap-4 items-center justify-center bg-gray-700 text-gray-100 text-lg px-2 font-semibold">
      <p>Add Balance</p>
      <span>&plus;</span>
    </button>
  </div>

  <div class="bg-gray-50 flex-1">
    <div class='p-5 font-bold'>Latest Transactions</div>
    <table class="w-full text-sm text-left text-gray-500">
        <thead class="text-center text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3">
                    From
                </th>
                <th scope="col" class="px-6 py-3">
                    Amount
                </th>
                <th scope="col" class="px-6 py-3">
                    Date
                </th>
            </tr>
        </thead>
        <tbody>
          
        </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class='flex justify-center content-center text-center flex-col w-auto'>
  <div class='font-bold pt-64 pb-10 text-5xl'> New User </div>
  <div class='flex w-96 justify-center content-center self-center'>
    <%= form_with model: @user, url: traders_path do |form| %>
      <div class="category-detail-list">
        <div class="category-add">
          <div class="field">
            <%= form.label :email, class: "text-left font-bold"%></br>
            <%= form.email_field :email, class: "block border-1 border-black" %>
          </div>
        </div>
        <div class="category-add">
          <div class="field"></br>
            <%= form.label :password, class: "font-bold" %></br>
            <%= form.password_field :password, class: "block border-1 border-black" %></br>
          </div>
        </div>
        <div class="category-add">
          <div class="field"></br>
            <%= form.label :password_confirmation, class: "font-bold" %></br>
            <%= form.password_field :password_confirmation, class: "block border-1 border-black" %></br>
          </div>
        </div>
      <div class="submit"></br>
        <button class='text-xl font-bold bg-cyan-500 uppercase p-1 rounded-2xl border-2 border-solid border-black w-48'><%= form.submit "Submit", class: "button-form" %></button>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='flex justify-center content-center text-center flex-col w-auto'>
  <div class='font-bold pt-64 pb-4 text-5xl'> TRADER <%= @user.id %></div>
  <div class='flex w-full justify-center content-center self-center text-center'>
    <div class="flex flex-col contect-center justify-center border-2 border-black h-80 w-2/6 m-auto">
      <div class="py-3 font-bold text-2xl"> <%= @user.email %> </div> 
      <div class="py-3 text-xl"> Created on <%= @user.created_at.to_time.strftime('%B %e at %l:%M %p') %> </div>
      <div class="py-3">
        <% if @user.pending == "waiting" %>
          <button class='text-xl font-bold  bg-red-400 uppercase p-1 rounded-2xl border-2 border-solid border-black w-32'> <%= @user.pending %> </button>
        <% else %>
          <button class='text-xl font-bold bg-green-400 uppercase p-1 rounded-2xl border-2 border-solid border-black w-32'> <%= @user.pending %> </button>
        <% end %>
        <button class='text-xl font-bold bg-green-400 uppercase p-1 rounded-2xl border-2 border-solid border-black w-16'> <%= link_to 'Edit', edit_trader_path(@user.id) %> </button>
      </div>
    </div>
  </div>
</div>