config/routes.rb
Rails.application.routes.draw do
  resources :stocks, only: [:index]
  resources :stock_transactions, only: [:new, :create, :index]
  resources :admin, only: [:index]
  resources :trader, controller: 'users'
  resources :transactions, only: [:create, :index]
  get 'transactions/new/:transaction_type(/:symbol)', to: 'transactions#new', as: 'new_transaction'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  namespace :market do
    resources :stocks, only: [:index, :show]
  end

  
  get 'home', to: 'static_pages#home'
  get 'admin/all', to: 'admin#all'
  get 'admin/transactions', to: 'admin#transactions'
  get 'admin/pending', to: 'admin#pending'
  get 'users/approval', to: 'users#approval'
  post 'traders', to: 'users#create'
  
  root "users#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :transactions
  has_many :shares
  has_many :users, through: :shares

  def data 
    self.chart == [] ? Stock.first.chart : self.chart
  end
end

app/controllers/market/stocks_controller.rb
class Market::StocksController < ApplicationController
  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :check_user
  before_action :check_pending

  def index
    unless user_signed_in?
      redirect_to home_path 
    else
      @shares = current_user.shares.includes(:stock)
    end
  end
end

app/helpers/market/stocks_helper.rb
module Market::StocksHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/market/stocks/index.html.erb
<div class="w-full h-full flex flex-col p-4 gap-4">
  <div class="h-[820px] bg-gray-50 flex flex-col rounded-lg">
    <div class="bg-gray-900 flex items-center justify-between p-4">
      <form>
        <input
          class="p-1 rounded-md"
          type="text"
          name="search"
          placeholder="AAPL or Apple"
        />
        <button type="submit" class="bg-gray-100 rounded-md p-1">Search</button>
      </form>
      <div class="flex gap-2">
        <button class="bg-gray-200 rounded-md text-grayj-900 p-2 font-bold">
          Most Recent
        </button>
        <button class="bg-gray-200 rounded-md text-grayj-900 p-2 font-bold">
          Gainers
        </button>
        <button class="bg-gray-200 rounded-md text-grayj-900 p-2 font-bold">
          Losers
        </button>
      </div>
    </div>
    <div class="w-full text-left text-gray-500 overflow-y-scroll flex-1">
      <table class="text-sm w-full">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3">Symbol</th>
            <th scope="col" class="px-6 py-3">Company Name</th>
            <th scope="col" class="px-6 py-3">Price</th>
            <th scope="col" class="px-6 py-3">Change Percent</th>
            <th scope="col" class="px-6 py-3">IEX Volume</th>
            <th scope="col" class="px-6 py-3">Change</th>
            <th scope="col" class="px-6 py-3">Latest Time</th>
          </tr>
        </thead>

        <tbody>
          <% @stocks.each do |stock| %>
            <tr class="bg-white border-b">
              <th
                scope="row"
                class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap"
              ><%= link_to stock.symbol, market_stock_path(stock.id) %></th>
              <td class="px-6 py-4"><%= stock.company_name %></td>
              <td class="px-6 py-4"><%= stock.price %></td>
              <td class="px-6 py-4"><%= stock.change_percent %></td>
              <td class="px-6 py-4"><%= stock.data.last["volume"] %></td>
              <td class="px-6 py-4"><%= stock.data.last["change"] %></td>
              <td class="px-6 py-4"><%= stock.data.last["label"] %></td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/market/stocks/show.html.erb
<div class="w-full h-full grid place-items-center p-8">
  <div class="bg-gray-200 rounded-xl h-full w-full flex flex-col gap-4 p-4">
    <div class="flex justify-between">
      <div class="flex gap-2">
        <div class="h-16 w-16 rounded-full bg-gray-500">
          <img src="<%= @stock.logo_url %>" class="rounded-full" alt="">
        </div>
        <div>
          <h3 class="text-2xl font-bold text-gray-900"><%= @stock.symbol %></h3>
          <p class="text-lg text-gray-500 font-medium"><%= @stock.company_name %></p>
        </div>
      </div>
      <div class="text-right">
        <h3 class="text-2xl font-extrabold text-gray-900">$<%= @stock.price %></h3>
        <h5 class="text-lg font-semibold text-green-500">
          &uarr; <%= @stock.change_percent %> 
        </h5>
      </div>
    </div>
    <div class="w-full flex-1 bg-gray-400">
      <p>GRAPH HERE</p>
    </div>
    <div class="flex justify-between w-full">
      <div class="flex gap-10 px-4">
        <div>
          <p class="text-gray-400 font-medium text-lg">Open</p>
          <h5 class="text-2xl text-gray-900 font-bold">$<%= @stock.chart.last["open"] %></h5>
        </div>

        <div>
          <p class="text-gray-400 font-medium text-lg">Day Low</p>
          <h5 class="text-2xl text-gray-900 font-bold">$<%= @stock.chart.last["low"] %></h5>
        </div>

        <div>
          <p class="text-gray-400 font-medium text-lg">Day High</p>
          <h5 class="text-2xl text-gray-900 font-bold">$<%= @stock.chart.last["high"] %></h5>
        </div>
      </div>
      <%=
        link_to 'Buy',
                  new_transaction_path('buy', @stock.symbol),
                  class:
                    'text-2xl font-bold p-4 px-8 rounded-lg bg-gray-900 text-gray-50'
      %>
    </div>
  </div>
</div>